@echo off
title Telegram Monitor Bot - Setup
color 0A
echo.
echo  =========================================
echo   Telegram Monitor Bot - Setup Wizard
echo  =========================================
echo.
echo  This wizard will create your config.py file.
echo  You can re-run this anytime to update settings.
echo.
echo  -----------------------------------------
echo   STEP 1 - Telegram API Credentials
echo   Get these from: https://my.telegram.org
echo  -----------------------------------------
echo.
set /p API_ID=  Enter your API_ID (numbers only): 
set /p API_HASH=  Enter your API_HASH: 
set /p PHONE=  Enter your phone number (e.g. +84912345678): 

echo.
echo  -----------------------------------------
echo   STEP 2 - Notification Bot
echo   Get BOT_TOKEN from @BotFather on Telegram
echo   Get NOTIFY_CHAT_ID from @userinfobot
echo  -----------------------------------------
echo.
set /p BOT_TOKEN=  Enter your BOT_TOKEN: 
set /p NOTIFY_CHAT_ID=  Enter your NOTIFY_CHAT_ID (numbers only): 

echo.
echo  -----------------------------------------
echo   STEP 3 - Group and Topic
echo   Find from Telegram Web URL:
echo   web.telegram.org/a/#-1002721004353_18
echo                       ^^^^^^^^^^^^^^ ^^
echo                       Group ID       Topic ID
echo  -----------------------------------------
echo.
set /p SOURCE_GROUP=  Enter GROUP ID (e.g. -1002721004353): 
set /p TOPIC_ID=  Enter TOPIC ID (e.g. 18): 

echo.
echo  -----------------------------------------
echo   STEP 4 - Target User
echo   Forward their message to @userinfobot
echo   to get their User ID
echo  -----------------------------------------
echo.
set /p USER_ID=  Enter Target User ID: 
set /p USER_NAME=  Enter a display name for this user (e.g. Main Caller): 

echo.
echo  -----------------------------------------
echo   STEP 5 - CA Check Bot (optional)
echo   Leave blank to skip
echo  -----------------------------------------
echo.
set /p BOT_ID=  Enter CA Check Bot ID (or press Enter to skip): 
set /p MC_THRESHOLD=  Market Cap threshold in USD (default 1000000): 

if "%MC_THRESHOLD%"=="" set MC_THRESHOLD=1000000
if "%BOT_ID%"=="" goto WRITE_CONFIG_NO_BOT

:WRITE_CONFIG_WITH_BOT
echo.
echo  Writing config.py...

(
echo # ============================================================
echo #  CONFIG - Auto-generated by setup wizard
echo #  To change settings, re-run 2_setup.bat
echo # ============================================================
echo.
echo API_ID   = %API_ID%
echo API_HASH = "%API_HASH%"
echo PHONE    = "%PHONE%"
echo.
echo BOT_TOKEN      = "%BOT_TOKEN%"
echo NOTIFY_CHAT_ID = %NOTIFY_CHAT_ID%
echo.
echo SOURCE_GROUP = %SOURCE_GROUP%
echo TOPIC_ID     = %TOPIC_ID%
echo.
echo TARGETS = [
echo     {
echo         "id": %USER_ID%,
echo         "name": "%USER_NAME%",
echo         "mode": "all",
echo     },
echo     {
echo         "id": %BOT_ID%,
echo         "name": "CA Check Bot",
echo         "mode": "filter",
echo         "filter": {
echo             "type": "marketcap",
echo             "keyword": "You are first",
echo             "max_value": %MC_THRESHOLD%,
echo         },
echo     },
echo ]
) > config.py

goto DONE

:WRITE_CONFIG_NO_BOT
echo.
echo  Writing config.py...

(
echo # ============================================================
echo #  CONFIG - Auto-generated by setup wizard
echo #  To change settings, re-run 2_setup.bat
echo # ============================================================
echo.
echo API_ID   = %API_ID%
echo API_HASH = "%API_HASH%"
echo PHONE    = "%PHONE%"
echo.
echo BOT_TOKEN      = "%BOT_TOKEN%"
echo NOTIFY_CHAT_ID = %NOTIFY_CHAT_ID%
echo.
echo SOURCE_GROUP = %SOURCE_GROUP%
echo TOPIC_ID     = %TOPIC_ID%
echo.
echo TARGETS = [
echo     {
echo         "id": %USER_ID%,
echo         "name": "%USER_NAME%",
echo         "mode": "all",
echo     },
echo ]
) > config.py

:DONE
echo.
echo  =========================================
echo   Setup complete! config.py has been created.
echo   Next step: Run 3_run.bat to start the bot
echo  =========================================
echo.
pause
